### ISSUE TITLE
Android Support (Nesting View Components)

### ISSUE THREAD

**Issue by blackwood** [Anthonyzou/react-native-html-to-text#2]
This module works great except the Android version of react-native expects you to not nest View components. I thought it could be solved by wrapping my call to HtmlText in a Layout, but this module also wraps Views in Views itself. The workaround could be sniffing for the platform in both places it's called:

```javascript
import { Platform } from 'react-native';

// ... Later, for example:
return (Platform.OS === 'android') ? (
  <Text style={this.props.containerStyle}>
    {children}
  </Text>
) : (
  <View style={this.props.containerStyle}>
    {children}
  </View>
)
```

**Comment by iagordevsquad** [comment]
Hello there, I don't know if you are still with this issue, but I guess the RN added support to nested View components, I think these components behaves like DIV of html.
